include_guard(GLOBAL)

set(CMAKE_CXX_STANDARD 20)

set(CMAKE_PCH_INSTANTIATE_TEMPLATES ON)
set(CMAKE_UNITY_BUILD ON)

set(HIDE_CMAKELISTS ON)

get_filename_component(FOLDER_NAME "${CMAKE_CURRENT_SOURCE_DIR}" NAME)

set(ENGINE_PATH "${CMAKE_SOURCE_DIR}" CACHE PATH "Path to the engine")
set(PLUGIN_NAME "${FOLDER_NAME}" CACHE STRING "Plugin name")
set(PLUGIN_LIBRARY_TYPE "SHARED" CACHE STRING "Plugin library type")
set(PLUGIN_API_KEY "${FOLDER_NAME}" CACHE STRING "Plugin api key name")
set(ENGINE_OUTPUT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Bin" CACHE STRING "Output path")

set_property(GLOBAL PROPERTY 
    USE_FOLDERS ON
)